# Generated by Django 6.0.6 on 2026-07-04 11:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('radius_m', models.IntegerField(default=1000, help_text='Analysis radius in meters')),
                ('business_type', models.CharField(choices=[('retail', 'Retail Store'), ('hospital', 'Hospital / Clinic'), ('ev_station', 'EV Charging Station'), ('warehouse', 'Warehouse / Logistics'), ('telecom', 'Telecom Tower'), ('renewable', 'Renewable Energy Project'), ('generic', 'Generic')], default='generic', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_requests', to='locations.savedlocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analysis_analysisrequest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_readiness_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('score_breakdown', models.JSONField(default=dict)),
                ('osm_data_snapshot', models.JSONField(default=dict)),
                ('ai_insights', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('raw_factors', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='analysis.analysisrequest')),
            ],
            options={
                'db_table': 'analysis_analysisresult',
            },
        ),
        migrations.CreateModel(
            name='WeightConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_type', models.CharField(max_length=100, unique=True)),
                ('weights', models.JSONField()),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analysis_weightconfig',
            },
        ),
    ]
