# Generated by Django 6.0.7 on 2026-07-31 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrequest',
            name='business_type',
            field=models.CharField(choices=[('pharmacy', 'Pharmacy / Medical Store'), ('stationery', 'Stationery / Book Store'), ('cafe', 'Cafe / Restaurant'), ('grocery', 'Grocery / Supermarket')], default='pharmacy', max_length=100),
        ),
    ]
