"""
intelligence/scoring/factors/accessibility.py

Accessibility factor — Phase 3 Final.

Changes from Phase 3.3:
  - Log normalization (diminishing returns) replaces linear scaling
  - Distance-weighted road and bus-stop scores via _get_weighted_count()
  - Road quality from RoadService (highway tag hierarchy)
  - Explanation generated by ExplainabilityBuilder (not inline)
"""

from __future__ import annotations

from .base import AbstractFactor
from intelligence.scoring.normalization import log_normalize, clamp
from intelligence.scoring.config import FACTOR_THRESHOLDS


class AccessibilityFactor(AbstractFactor):
    """Scores location based on road quality and public transit access."""

    key = "accessibility"

    def compute(self) -> tuple[float, dict]:
        cfg = FACTOR_THRESHOLDS["accessibility"]

        # Use weighted count when enriched data available (distance-aware)
        roads     = self._get_weighted_count("roads")
        bus_stops = self._get_weighted_count("bus_stops")

        # Log normalization — 200 roads ≠ automatic 100%
        roads_score = log_normalize(roads,     cfg["roads_saturation"])
        bus_score   = log_normalize(bus_stops, cfg["bus_stops_saturation"])

        score = clamp(
            cfg["roads_weight"]     * roads_score +
            cfg["bus_stops_weight"] * bus_score
        )

        # Gather enriched metadata for ExplainabilityBuilder
        road_features = self._get_features("roads")
        road_hierarchy: dict = {}
        if road_features:
            from intelligence.scoring.services.roads import RoadService
            from intelligence.scoring.services.distance import get_distance_service
            road_hierarchy = RoadService.analyse(
                road_features, self.lat, self.lon, self.radius_m,
                distance_service=get_distance_service(),
            )

        raw = {
            "key":   self.key,
            "label": "Accessibility",
            "score": round(score, 2),
            "inputs": {
                "roads":     self._get_count("roads"),
                "bus_stops": self._get_count("bus_stops"),
            },
            "sub_scores": {
                "roads_weighted":     round(roads,       3),
                "bus_stops_weighted": round(bus_stops,   3),
                "roads_score":        round(roads_score, 2),
                "bus_score":          round(bus_score,   2),
            },
            "road_hierarchy": road_hierarchy,
            "nearest_distance": {
                "roads":     self._get_nearest_distance("roads"),
                "bus_stops": self._get_nearest_distance("bus_stops"),
            },
            "density": {
                "roads":     self._get_density("roads"),
                "bus_stops": self._get_density("bus_stops"),
            },
        }
        return score, raw
