"""
intelligence/spatial/osm/config.py

Schema configuration and category mappings based on discovered PostGIS schema.
"""

from typing import Dict, List, Set

# Discovered PostgreSQL/PostGIS table names generated by osm2pgsql
TABLE_POINT = "planet_osm_point"
TABLE_LINE = "planet_osm_line"
TABLE_POLYGON = "planet_osm_polygon"
TABLE_ROADS = "planet_osm_roads"

# Discovered SRID of geometry column 'way'
GEOM_SRID = 3857

# OSM Tag -> Obrix Category mapping (identical to OverpassClient for 100% parity)
CATEGORY_TAG_MAP: Dict[str, Dict[str, Set[str]]] = {
    "roads": {
        "highway": {
            "motorway", "trunk", "primary", "secondary",
            "tertiary", "residential", "unclassified", "living_street"
        }
    },
    "hospitals": {
        "amenity": {"hospital", "clinic", "doctors", "nursing_home"}
    },
    "schools": {
        "amenity": {"school", "college", "university", "kindergarten", "language_school"}
    },
    "bus_stops": {
        "highway": {"bus_stop"},
        "public_transport": {"stop_position"},
    },
    "parks": {
        "leisure": {"park"},
        "landuse": {"park", "recreation_ground", "village_green"},
    },
    "fuel_stations": {
        "amenity": {"fuel"}
    },
    "restaurants": {
        "amenity": {"restaurant", "fast_food", "cafe", "food_court", "pub", "bar"}
    },
    "banks": {
        "amenity": {"bank", "atm", "bureau_de_change"}
    },
}
