"""
intelligence/scoring/types.py

Data-transfer objects for the scoring engine — Phase 3 Final.

ScoreResult gains confidence, distance_metrics, density_metrics,
road_hierarchy, competition_metrics, and normalization_metadata.
All new fields have default_factory=dict for backwards compatibility.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class FactorScore:
    """
    The computed output of a single scoring factor.

    key          : machine-readable factor identifier
    label        : human-readable display name
    score        : 0–100 (log-normalized, Phase 3 Final)
    explanation  : generated by ExplainabilityBuilder (not the factor itself)
    inputs       : raw inputs used (for debugging / ML training)
    sub_scores   : per-component intermediate scores
    """
    key:         str
    label:       str
    score:       float
    explanation: str
    inputs:      dict[str, Any] = field(default_factory=dict)
    sub_scores:  dict[str, float] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "key":         self.key,
            "label":       self.label,
            "score":       round(self.score, 2),
            "explanation": self.explanation,
            "inputs":      self.inputs,
            "sub_scores":  {k: round(v, 2) if isinstance(v, float) else v
                            for k, v in self.sub_scores.items()},
        }


@dataclass
class ScoreResult:
    """
    Complete output of one ScoringEngine.calculate() call.

    Phase 3 Final new fields (all optional, default to empty dict):
        confidence          : {score, label, penalties, is_enriched}
        distance_metrics    : per-category nearest/average distance in metres
        density_metrics     : per-category features/km²
        road_hierarchy      : quality_score, dominant_type, road_type_counts, ...
        competition_metrics : competitor_count, breakdown, weighted_pressure
        normalization_metadata : method used, decay rate, radius
    """
    overall:       float
    factors:       dict[str, FactorScore]
    weights_used:  dict[str, float]
    business_type: str

    # Phase 3 Final extensions
    confidence:               dict[str, Any] = field(default_factory=dict)
    distance_metrics:         dict[str, Any] = field(default_factory=dict)
    density_metrics:          dict[str, Any] = field(default_factory=dict)
    road_hierarchy:           dict[str, Any] = field(default_factory=dict)
    competition_metrics:      dict[str, Any] = field(default_factory=dict)
    normalization_metadata:   dict[str, Any] = field(default_factory=dict)

    # ── Serialisation helpers ─────────────────────────────────────────────────

    def to_score_breakdown(self) -> dict[str, float]:
        """Flat {factor_key: score} — stored in score_breakdown DB field."""
        return {k: round(v.score, 2) for k, v in self.factors.items()}

    def to_raw_factors(self) -> dict[str, Any]:
        """
        Full factor detail plus _meta — stored in raw_factors DB field.

        _meta contains the extended metrics so the serialiser can expose them
        as top-level API fields without adding new DB columns.
        """
        out: dict[str, Any] = {k: v.to_dict() for k, v in self.factors.items()}
        out["_meta"] = {
            "confidence":             self.confidence,
            "distance_metrics":       self.distance_metrics,
            "density_metrics":        self.density_metrics,
            "road_hierarchy":         self.road_hierarchy,
            "competition_metrics":    self.competition_metrics,
            "normalization_metadata": self.normalization_metadata,
        }
        return out

    def to_dict(self) -> dict[str, Any]:
        """Full structured dict — JSON-serialisable."""
        return {
            "overall":                round(self.overall, 2),
            "business_type":          self.business_type,
            "weights_used":           self.weights_used,
            "confidence":             self.confidence,
            "distance_metrics":       self.distance_metrics,
            "density_metrics":        self.density_metrics,
            "road_hierarchy":         self.road_hierarchy,
            "competition_metrics":    self.competition_metrics,
            "normalization_metadata": self.normalization_metadata,
            "factors": {k: v.to_dict() for k, v in self.factors.items()},
        }
